### ISSUE TITLE
Can't get keter to not try to bind to port 80

### ISSUE THREAD

**Issue by bitemyapp** [snoyberg/keter#137]
```
vagrant@vagrant-base-trusty-amd64:/opt/keter$ sudo -u root strace -f -e trace=bind /opt/keter/bin/keter /opt/keter
Process 14863 attached
Process 14864 attached
Process 14865 attached
Process 14866 attached
[pid 14862] --- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TIMER, si_pid=0, si_uid=0, si_value=0} ---
[pid 14862] --- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TIMER, si_pid=0, si_uid=0, si_value=0} ---
[pid 14862] --- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TIMER, si_pid=0, si_uid=0, si_value=0} ---
Process 14867 attached
[pid 14862] --- SIGVTALRM {si_signo=SIGVTALRM, si_code=SI_TIMER, si_pid=0, si_uid=0, si_value=0} ---
[pid 14867] bind(16, {sa_family=AF_NETLINK, pid=0, groups=00000000}, 12) = 0
Process 14868 attached
[pid 14867] bind(16, {sa_family=AF_INET, sin_port=htons(80), sin_addr=inet_addr("0.0.0.0")}, 16) = -1 EADDRINUSE (Address already in use)
[pid 14867] bind(16, {sa_family=AF_INET6, sin6_port=htons(80), inet_pton(AF_INET6, "::", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, 28) = -1 EADDRINUSE (Address already in use)
keter: bind: resource busy (Address already in use)
[pid 14864] +++ exited with 0 +++
[pid 14863] +++ exited with 0 +++
[pid 14867] +++ exited with 0 +++
[pid 14868] +++ exited with 0 +++
[pid 14865] +++ exited with 1 +++
[pid 14862] +++ exited with 1 +++
+++ exited with 0 +++
```

# Config

## Keter

```yaml
root: ../
listeners:
    - host: "localhost"
      port: 8111 # Could be used to modify port
```

Setting top-level port didn't help.

## App

```yaml
stanzas:
  - type: webapp
    # Name of your executable. You are unlikely to need to change this.
    # Note that all file paths are relative to the keter.yml file.
    exec: ../dist/build/hestia/hestia

    # Command line options passed to your application.
    args: []

    hosts:
      # You can specify one or more hostnames for your application to respond
      # to. The primary hostname will be used for generating your application
      # root.
      - betterteam.com
      - app.betterteam.com
      - localhost
    # Enable to force Keter to redirect to https
    # Can be added to any stanza
    requires-secure: false

  # Static files.
  - type: static-files
    hosts:
      - static.betterteam.com
      - app.betterteam.com
      - localhost
    root: ../static
```

What am I doing wrong here? Everything keter is in `/opt/keter` and it's running as root, if that changes anything.
