### ISSUE TITLE
keter silently not logging

### ISSUE THREAD

**Issue by silky** [snoyberg/keter#142]
has anyone seen this?

i'm using keter built from this repo:

```
> keter --version
keter version: 1.4.3.1
```

it runs

it says my host is not found

and it emits _no_ log entries

it makes the files

keter-config

```
root: ..
listeners:
    # HTTP
    - host: "*4" # Listen on all IPv4 hosts
      port: 8000 # Could be used to modify port
    # HTTPS
    # - host: "*4"
      #port: 443
      # key: key.pem
      # certificate: certificate.pem
```
