### ISSUE TITLE
SSL breaks redirects on Chrome

### ISSUE THREAD

**Issue by dariooddenino** [snoyberg/keter#181]
Hi, my app has a pretty basic config:

`keter-config.yml`:
```
root: ..

listeners:
    # HTTP
    - host: "*4" # Listen on all IPv4 hosts
      #port: 80 # Could be used to modify port
    # HTTPS
    - host: "*4"
      port: 443
      key: cert/my.key
      certificate: cert/my.crt
```

`keter.yml`:
```
stanzas:
  - type: webapp
    exec: ../dist/bin/my-app

    args: []

    hosts:
      - staging.myapp.com

    requires-secure: false
    # ssl: true

  # Static files.
  - type: static-files
    hosts:
      - static.myapp.com
    root: ../static
``

Everything works fine on every browser I could test, except for chrome. If I navigate the https version of my site, all redirects stop working.
What happens is that the same page is reloaded.

By setting `ssl: true` I can still get the initial http -> https redirect working, but all redirects afterwards continue having this problem.

I'm on Ubuntu 16.04. Is there a way to get the built keter version? I can't find it.

Thanks!
