### ISSUE TITLE
Error occurred when launching bundle server: ensureAlive failed

### ISSUE THREAD

**Issue by SongWithoutWords** [snoyberg/keter#189]
I'm having trouble deploying a Yesod app with Keter on a Ubuntu 18.04 VM hosted by Google Cloud Platform, using the sqlite scaffold as a jumping off point. I compiled both the Yesod app and Keter on my own machine, running the same version of Ubuntu.

When I visit the IP of my site, I am greeted by:
> Welcome to Keter
> The hostname you have provided, 104.198.13.16, is not recognized.

It seems that the Yesod App has timed out after a minute, based on the contents of `/opt/keter/log/keter/current.log`:

```
2018-10-22 08:06:55.34: Unpacking bundle '/opt/keter/etc/../incoming/server.keter'
2018-10-22 08:06:55.66: Sanity checks passed
2018-10-22 08:06:55.66: Reserving hosts for app server: 104.198.13.16
2018-10-22 08:06:55.66: Process created: /opt/keter/temp/server-0/dist/bin/server
2018-10-22 08:08:26.66: Forgetting host reservations for app server: 104.198.13.16
2018-10-22 08:08:26.67: Error occured when launching bundle server: ensureAlive failed
CallStack (from HasCallStack):
  error, called at ./Keter/App.hs:331:14 in keter-1.4.3.2-4FXhcevLhnt270CSYCVtlD:Keter.App
```

The contents of `/opt/keter/log/app-server/current.log are as follows (it doesn't seem like the app is crashing):
```
Migrating: CREATE TABLE "user"("id" INTEGER PRIMARY KEY,"ident" VARCHAR NOT NULL,"password" VARCHAR NULL,CONSTRAINT "unique_user" UNIQUE ("ident"))
Migrating: CREATE TABLE "email"("id" INTEGER PRIMARY KEY,"email" VARCHAR NOT NULL,"user_id" INTEGER NULL REFERENCES "user","verkey" VARCHAR NULL,CONSTRAINT "unique_email" UNIQUE ("email"))
Migrating: CREATE TABLE "comment"("id" INTEGER PRIMARY KEY,"message" VARCHAR NOT NULL,"user_id" INTEGER NULL REFERENCES "user")
Migrating: CREATE TABLE "x_user"("id" INTEGER PRIMARY KEY,"email" VARCHAR NOT NULL,"password_hash" VARCHAR NOT NULL,"salt" VARCHAR NOT NULL,"data" VARCHAR NOT NULL,CONSTRAINT "user_email" UNIQUE ("email"))
Migrating: CREATE TABLE "doctor"("id" INTEGER PRIMARY KEY,"first_name" VARCHAR NOT NULL,"last_name" VARCHAR NOT NULL)
Migrating: CREATE TABLE "patient"("id" INTEGER PRIMARY KEY,"first_name" VARCHAR NOT NULL,"last_name" VARCHAR NOT NULL,"date_of_birth" DATE NULL)
Migrating: CREATE TABLE "doctor_patient_request"("id" INTEGER PRIMARY KEY,"doctor" INTEGER NOT NULL REFERENCES "doctor","patient" INTEGER NOT NULL REFERENCES "patient",CONSTRAINT "unique_request" UNIQUE ("patient","doctor"))
Migrating: CREATE TABLE "doctor_patient_relation"("id" INTEGER PRIMARY KEY,"doctor" INTEGER NOT NULL REFERENCES "doctor","patient" INTEGER NOT NULL REFERENCES "patient",CONSTRAINT "unique_relation" UNIQUE ("patient","doctor"))
Migrating: CREATE TABLE "prescription"("id" INTEGER PRIMARY KEY,"medication" VARCHAR NOT NULL)
```
The contents of the /opt/keter directory are :
```
./bin:
keter*
./etc:
keter-config.yaml  key.pem
./incoming:
server.keter
```
The contents of `opt/keter/keter-config.yaml` are (I've tried both with and without the port):
```
root: ..
listeners:
    - host: "*4" # Listen on all IPv4 hosts
      port: 80 # Could be used to modify port
setuid: root
```
The contents of `config/keter.yml` are:
```
user-edited: true
stanzas:
  - type: webapp
    exec: ../dist/bin/server
    args: []
    hosts:
      - 104.198.13.16
    requires-secure: false
  - type: static-files
    hosts:
      - 104.198.13.16
    root: ../static
```

Does anyone have any ideas?
