### ISSUE TITLE
Configuring IPv4 and IPv6  to listen on the same port?

### ISSUE THREAD

**Issue by achirkin** [snoyberg/keter#192]
The basic example of `keter-config.yaml` suggests to listen IPv4 interfaces only:
```yaml
listeners:
    - host: "*4"
      port: 80
```
If I add another listener:
```yaml
listeners:
    - host: "*4"
      port: 80
    - host: "*6"
      port: 81
```
then everything works fine - keter is accessible on `http://[ipv6::addr]:81/`. However, if I try to use port 80 for both listeners, keter does not start. If I remove "4" from the host line:
```yaml
listeners:
    - host: "*"
      port: 80
```
then keter listens on IPv4 only.

Is there a way to make keter listen both IPv4 and IPv6 on the same port?
