### ISSUE TITLE
redirect is broken on Chrome (if use SSL)

### ISSUE THREAD

**Issue by timCF** [snoyberg/keter#194]
I have a problem with yesod application deployed with keter. Can be reproduced with Google Chrome browser. 

server
- ubuntu-16.04
- keter lts-7.19
- yesod lts-11.22

client
- macOS 10.14.2
- Google Chrome 72.0.3626.81

Problematic site itself is online and issue can be reproduced with one step in Google Chrome private tab with link https://rentier.ml/merchant/create which should redirect to https://rentier.ml/auth/login (but browser can't handle it).

Site works good on HTTP. But when HTTPS is enabled - browser can load page, but can not handle redirects from one page to other. In other browsers (Safari, Firefox) site works perfect. In Google Chrome error looks like this 

![screenshot 2019-02-05 at 00 11 13](https://user-images.githubusercontent.com/7428479/52240811-a48a0100-28da-11e9-98ca-97d28ac38fe4.png)

I tried to debug with chrome://net-export/ but I'm not very familiar with this util.. I can say only that browser is cancelling request because of some reason:

```
{"params":{"active_streams":1,"debug_data":"this frame is not allowed in an idel stream","error_code":"1 (PROTOCOL_ERROR)","last_accepted_stream_id":3,"unclaimed_streams":0},"phase":0,"source":{"id":42107,"type":9},"time":"14669686","type":192},
{"params":{"description":"Abandoned.","net_error":"ERR_ABORTED","stream_id":5},"phase":0,"source":{"id":42177,"type":1},"time":"14669686","type":217},
```

Keter config on server **/opt/keter/etc/keter-config.yaml**

```
root: ..
listeners:
    # HTTP
    - host: "*4" # Listen on all IPv4 hosts
      port: 80 # Could be used to modify port
    # HTTPS
    - host: "*4"
      port: 443
      key: /etc/letsencrypt/live/rentier.ml/privkey.pem
      certificate: /etc/letsencrypt/live/rentier.ml/fullchain.pem
```

Keter config of application

```
stanzas:
  - type: webapp
    exec: ../dist/bin/rentier
    args: []
    forward-env:
      - GMAIL_CLIENT_ID
      - GMAIL_CLIENT_SECRET
      - FIREBASE_API_KEY
      - FIREBASE_PROJECT_ID
      - FIREBASE_MSG_SENDER_ID
    hosts:
      - rentier.ml
    requires-secure: true
  - type: static-files
    hosts:
      - static.rentier.ml
    root: ../static
plugins:
  postgres: true
```
