### ISSUE TITLE
base url to www redirection doesn't work

### ISSUE THREAD

**Issue by felipexpert** [snoyberg/keter#197]
this is my keter:
```
# After you've edited this file, remove the following line to allow
# `yesod keter` to build your bundle.
user-edited: false

# A Keter app is composed of 1 or more stanzas. The main stanza will define our
# web application. See the Keter documentation for more information on
# available stanzas.
stanzas:

  # Your Yesod application.
  - type: webapp

    # Name of your executable. You are unlikely to need to change this.
    # Note that all file paths are relative to the keter.yml file.
    #
    # The path given is for Stack projects. If you're still using cabal, change
    # to
    # exec: ../dist/build/my-project/my-project
    exec: ../dist/bin/my-project

    # Command line options passed to your application.
    args: []

    hosts:
      # You can specify one or more hostnames for your application to respond
      # to. The primary hostname will be used for generating your application
      # root.
      - www.my-project.com

    # Enable to force Keter to redirect to https
    # Can be added to any stanza
    requires-secure: false

  # Static files.
  - type: static-files
    hosts:
      - static.my-project.com
    root: ../static

    # Uncomment to turn on directory listings.
    # directory-listing: true

  # Redirect plain domain name to www.
  - type: redirect

    hosts:
      - my-project.com
    actions:
      - host: www.my-project.com
        # secure: false
        # port: 80

    # Uncomment to switch to a non-permanent redirect.
    # status: 303

# Use the following to automatically copy your bundle upon creation via `yesod
# keter`. Uses `scp` internally, so you can set it to a remote destination
# copy-to: user@host:/opt/keter/incoming/

# You can pass arguments to `scp` used above. This example limits bandwidth to
# 1024 Kbit/s and uses port 2222 instead of the default 22
# copy-to-args:
#   - "-l 1024"
#   - "-P 2222"

# If you would like to have Keter automatically create a PostgreSQL database
# and set appropriate environment variables for it to be discovered, uncomment
# the following line.
# plugins:
#   postgres: true
```

It doesn't redirect https://dinhonesto.com.br to https://www.dinhonesto.com.br (although http is redirecting to https all right)

this is my keter configuration on the server:

```
# Directory containing incoming folder, where to store logs, etc. Relative to
# the config file directory.
root: ..

# Keter can listen on multiple ports for incoming connections. These ports can
# have HTTPS either enabled or disabled.
listeners:
    #- host: "medital.com.br"
    #  actions:
    #      - host: "medital.com.br"
    #        port: 8080 # Could be used to modify port
    # HTTP
    - host: "*4" # Listen on all IPv4 hosts
      port: 80 # Could be used to modify port
    - host: "*4" # Listen on all IPv4 hosts
      port: 443 # Could be used to modify port
      key: /opt/keter/etc/cert/private.key
      certificate: /opt/keter/etc/cert/certificate.crt
    - host: "*4" # Listen on all IPv4 hosts
      port: 3000 # Could be used to modify port
    - host: "*4" # Listen on all IPv4 hosts
      port: 3001 # Could be used to modify port
      key: /opt/keter/etc/cert/private.key
      certificate: /opt/keter/etc/cert/certificate.crt
      #key: /opt/keter/etc/cert/dinhonesto.com.br.dec.key
      #certificate: /opt/keter/etc/cert/dinhonesto.com.br.crt
    # HTTPS
    #- host: "*4"
      #port: 443
      #key: key.pem
      #certificate: certificate.pem

redirects:
    - from: dinhonesto.com.br
      to: www.dinhonesto.com.br

# User to run applications as

# setuid: ubuntu

# Get the user's IP address from x-forwarded-for. Useful when sitting behind a
# load balancer like Amazon ELB.

# ip-from-header: true
```
