### ISSUE TITLE
One domain, many applications.

### ISSUE THREAD

**Issue by user-b** [snoyberg/keter#205]
Hello. I'm running a simple application with:

```
stanzas:
    - type: webapp
      exec: ../mysite-exe
      hosts:
        - www.mysite.com
        - mysite.com
      env:
        FROM_KETER_CONFIG: PORT
```

It works fine but I'd like to add another executable either at wathever.mysite.com or mysite.com/wathever. Can this be done with keter? Thank you.
