### ISSUE TITLE
set working directory for applications?

### ISSUE THREAD

**Issue by jwaldmann** [snoyberg/keter#212]
I don't quite see what the working directory is for `webapp` or `background` process started by keter, and how I could change it via config.

Probably I should rewrite my app so that it does not use relative filepaths ... When  it wants to read a config file on start-up that I am specifiying as a command line argument. This seems to work (in config/keter.yml)
```
stanzas:
  - type: background
    exec: ../bin/my-application
    args:
      - -c
      - config/config.yml
```
but it's somewhat funny: location of exec is relative to location  of this config file, while CWD seems to be one level up (as my app's config file is relative to that) Well at least it'd be good to have this documented, and this issue is proxy for that.
