### ISSUE TITLE
Out of memory error when running keter on server

### ISSUE THREAD

**Issue by maheshkronecker** [snoyberg/keter#288]
Hello. 

When I upload a keter bundle to `/opt/keter/incoming` and run

```bash
sudo /opt/keter/bin/keter /opt/keter/etc/keter-config.yaml
```

I get the following message :

`process stopped` (after 15 seconds, more if I create a swap file).

I am a bit baffled, as everything was working well and my site was up and running with the same configuration, until it simply stopped working.

```bash
grep -i kill /var/log/*

/var/log/syslog:2024-03-07T10:46:16.278207+01:00 debian kernel: [ 5841.835003] ghc_ticker invoked oom-killer: gfp_mask=0x140cca(GFP_HIGHUSER_MOVABLE|__GFP_COMP), order=0, oom_score_adj=0
/var/log/syslog:2024-03-07T10:46:16.278886+01:00 debian kernel: [ 5841.835152]  oom_kill_process.cold+0xb/0x10
/var/log/syslog:2024-03-07T10:46:16.279094+01:00 debian kernel: [ 5841.835531] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/user.slice/user-1001.slice/session-10.scope,task=keter,pid=1796,uid=0
/var/log/syslog:2024-03-07T10:46:16.279095+01:00 debian kernel: [ 5841.835567] Out of memory: Killed process 1796 (keter) total-vm:1074014088kB, anon-rss:3734684kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:7444kB oom_score_adj:0
/var/log/syslog:2024-03-07T10:46:16.305854+01:00 debian systemd[1]: session-10.scope: A process of this unit has been killed by the OOM killer.
```

```
cat etc/keter-config.yaml
```

```yaml
root: ..

rotate-logs: true

listeners:
    - host: "*4" # Listen on all IPv4 hosts

    - host: "*4"
      key: /etc/appa/privkey.pem
      certificate: /etc/appa/fullchain.pem
      session: true
```

The error persists if I remove the https listener in the yaml file.
