### ISSUE TITLE
Keter with ssl listener silently failing to start

### ISSUE THREAD

**Issue by dbp** [snoyberg/keter#34]
My keter-config.yaml looks like this:

```
root: ..

listeners:
    - host: "*4" 
      port: 81
    - host: "*4"
      port: 10000
      key: /opt/keter/ssl/ssl.key
      certificate: /opt/keter/ssl/ssl.crt

setuid: host
```

When I start keter, ie with `/opt/keter/bin/keter /opt/keter/etc/keter-config.yaml`, it immediately quits, with nothing printed to stderr and nothing written to its log file. Note that even if there is nothing in the incoming folder, it fails to start.

ssl.crt is a chained certificate (ie, a few intermediaries and the certificate itself), while ssl.key is a standard RSA key. 

I'm not sure how to debug this further - as I don't know what's going wrong, and as far as I can tell, I'm doing what's in the docs / what I have gleaned from the source code (and if I leave out either certificate or key, I get the expected complaint that they must both be present).

Any thoughts or potential troubleshooting?
