### ISSUE TITLE
Keter Does Not Setup Postgres Database In V1.0 Config Format

### ISSUE THREAD

**Issue by creichert** [snoyberg/keter#46]
Discussion on mailing list here: https://groups.google.com/forum/#!topic/yesodweb/4I8xrpnSlCM

Here are the configuration posted by geoff in the mailing list discussion,

The working 'v.4' version:

```
exec: ../dist/build/test/test
args:
    - production
host: keter.test.com
ssl:  true
postgres: true
```

The v1.0 which does not work for me:

```
stanzas:
    - type: webapp
      exec: ../dist/build/test/test
      args:
        - production
      hosts:
        - keter.test.com
      ssl:  true
      postgres: true


exec: ../dist/build/test/test
postgres: true

```
