### ISSUE TITLE
Subdomains Overwritten Across Bundles

### ISSUE THREAD

**Issue by creichert** [snoyberg/keter#72]
I have two bundles.

Bundle A:

```
stanzas:
    - type: webapp
      exec: ../dist/build/app/app
      hosts:
          - someapp.com
```

Bundle B:
```
stanzas:
    - type: webapp
      exec: ../dist/build/api/api
      hosts:
          - api.someapp.com
```

Each time bundle A is pushed, bundle B's host is overwritten (e.g. The specified host `api.someapp.com` could not be found).

I have looked into this a bit without much luck. I'm primarily focused around the reserveHost function: https://github.com/snoyberg/keter/blob/46399027e253fd3edb2461526dbe606d38b45253/Keter/HostManager.hs#L59
