### ISSUE TITLE
Host name not recognized

### ISSUE THREAD

**Issue by MonrealRyan** [snoyberg/keter#79]
On my last issue [#78](https://github.com/snoyberg/keter/issues/78)

i resolved the keter but once i run my site it gives me this.

```
Welcome to Keter

The hostname you have provided, www.mysite.com, is not recognized.

```

**Comment by creichert** [comment]
You need to add the host to your bundles keter config: https://github.com/snoyberg/keter/blob/master/incoming/foo1_0/config/keter.yaml#L12

You can also try putting the IP there to start testing.

Can you post the contents of your apps configuration?

**Comment by creichert** [comment]
What kind of app are you running? Here is the default keter configuration for the yesod-scaffold, maybe the commentary helps? https://github.com/yesodweb/yesod-scaffold/blob/postgres/config/keter.yml#L24

**Comment by MonrealRyan** [comment]
@creichert  - I already configured it.. but doesn't work

**Comment by creichert** [comment]
It's going to be difficult to debug without an example of your configuration.

The error you are receiving is cause by not having a valid app with that domain name. Did you check your log files?

Can you post the output from your `log/keter/current.log` and the corresponding apps (relevant) logging.


You should also try adding the IP address to the list of hosts.

**Comment by creichert** [comment]
My current guess is that the app is failing to execute for some reason. The logging output might indicate why.

**Comment by MonrealRyan** [comment]
this is the error

```
2015-03-07 01:40:26.95: Unpacking bundle '/opt/keter/etc/../incoming/Main.keter'
```

**Comment by creichert** [comment]
What's in the logfile for the app? `/opt/keter/log/Main/current.log`. Keter is relaying that message through it's own logging.

**Comment by creichert** [comment]
Also, that's not a keter error. That output happens each time a bundle is unpacked. Was there another error around that?

**Comment by MonrealRyan** [comment]
No keter error at all?

**Comment by creichert** [comment]
There is only so much I can do with little feedback.

If there is no Keter error at all for that particular app, then it is probably not executing it correctly. It might also be incorrectly bundled.

How are you creating the app? Note that a keter bundle needs a specific directory structure to even be processed:

```
tar czfv wedapp.keter dist/build/wedapp/wedapp config/
```

There needs to be a `config/keter.yml` file and the path your specify to your app needs to be identical to what's in the `exec` field of your bundles config. What does your `exec` option say in your apps configuration?

Have you created a test bundle to verify?  You could try using the Yesod scaffold i linked to directly.

Have you been through the README? Is there a particular point there you think you might be stuck on?

**Comment by MonrealRyan** [comment]
@creichert - Hi sorry very late response. I got this error.
```
2015-03-07 19:33:38.60: Error occured when launching bundle Main: ExecutableNotFound (FilePath "/opt/keter/etc/../temp/Main-0/config/../worker")
```

**Comment by creichert** [comment]
@MonrealRyan Ok, looks like an incorrectly configured bundle. It seems to be looking in the config/.. directory for the exe. You need to go one more directory up (the `exec` PATH is relative to the `config` directory (see 2))

Can you verify that:

1) The executable is actually being stored in the *.keter bundle? See my `tar` command above. The `dist/build/wedapp/wedapp`

2) The `exec` field in the keter bundle is a relative path from the `config/` directory to the exe. e.g.
`exec: ../dist/build/wedapp/wedapp` works when the project root contains `config` and `dist`


Is the worker executable stored in the project root?

**Comment by MonrealRyan** [comment]
@creichert  - My ```tar.gz``` was provided by the fpcomplete IDE. So i just create a keter from it..

from that I unzip the ```.tar.gz ```
```
$ ls
$ config  LICENSES.txt  Main  Main.tar.gz  README.md  src  static  templates
```

for ```config`` folder here is the list
```
$ ls
$ keter.yaml  routes
```

the ```keter.yaml`` file
```
stanzas:
    - type: webapp
      exec: ../../Main
      args:
        - weedreporter v1.0
      #ssl : true
      env:
        FROM_KETER_CONFIG: developement production
      forward-env:
        - FROM_SYSTEM_ENV
        - ANOTHER_ENV_VAR
      hosts:
        - www.mysite.com
        - mysite.com
        - ip address of my instance don't know if required so i just added it

    - type: background
      exec: ../worker
      args:
        - Keter Background Worker
      env:
        FROM_KETER_CONFIG: foo bar baz
      restart-count: 10
      restart-delay-seconds: 6

    - type: static-files
      host: unsafe1_1_0
      directory-listing: true
      requires-secure: true
      root: ../../

    - type: static-files
      host: unsafe2_1_0
      root: /home
      #directory-listing: true
      middleware:
         - autohead
         - accept-override
         - jsonp
         - method-override
         - method-override-post
         - local:
             status : 405
             message: "Keter Rocks (local status message)"
         - basic-auth:
              realm: "Keter Basic Auth"
              creds:
                 jon : rocks
                 bla : dada
         - headers:
             Access-Control-Allow-Origin : "*"

    - type: reverse-proxy
      reversed-host: www.yesodweb.com
      reversed-port: 80
      reversing-host: localhost

plugins:
    #postgres: true

```

then do the ``` tar ``` you recommend
but I change the ff:
1. wedapp.keter to Main.Keter
2. dist/build/wedapp/wedapp to Main
3. then add the static folder in it
```
$ tar czfv wedapp.keter Main config/ static/
```
then i copy the Main.keter to ```/opt/keter/incomin/```

- Question
   - Is the worker executable stored in the project root?
- Answer
    - are you talking about the unzip file of my ```.tar.gz``` its on my /home/ubuntu/sites/mysite/mysite dir

**Comment by creichert** [comment]
Thanks for the output. I still need to look into this but it would be a good idea to minimize the keter file to only what is needed.

```
stanzas:
    - type: webapp
      exec: ../Main
      args:
        - weedreporter v1.0
      hosts:
        - ip address of my instance don't know if required so i just added it

```


Are you running this on a remote server? You probably don't have access to `www.mysite.com`, right?

Can you send me a link to the FP Complete project?
